/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicOfflineRouteImport } from './routes/_public/offline'
import { Route as AuthedFavoritesRouteImport } from './routes/_authed/favorites'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as PublicShowsIndexRouteImport } from './routes/_public/shows/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApiWebhooksMuxRouteImport } from './routes/api/webhooks/mux'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicWatchSlugRouteImport } from './routes/_public/watch/$slug'
import { Route as PublicShowsSlugRouteImport } from './routes/_public/shows/$slug'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminCommentsRouteImport } from './routes/_authed/admin/comments'
import { Route as AuthedAdminVideosIndexRouteImport } from './routes/_authed/admin/videos/index'
import { Route as AuthedAdminSeriesIndexRouteImport } from './routes/_authed/admin/series/index'
import { Route as AuthedAdminVideosNewRouteImport } from './routes/_authed/admin/videos/new'
import { Route as AuthedAdminSeriesNewRouteImport } from './routes/_authed/admin/series/new'
import { Route as AuthedAdminVideosIdEditRouteImport } from './routes/_authed/admin/videos/$id.edit'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOfflineRoute = PublicOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedFavoritesRoute = AuthedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const PublicShowsIndexRoute = PublicShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const ApiWebhooksMuxRoute = ApiWebhooksMuxRouteImport.update({
  id: '/api/webhooks/mux',
  path: '/api/webhooks/mux',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicWatchSlugRoute = PublicWatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicShowsSlugRoute = PublicShowsSlugRouteImport.update({
  id: '/shows/$slug',
  path: '/shows/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminCommentsRoute = AuthedAdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminVideosIndexRoute = AuthedAdminVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminSeriesIndexRoute = AuthedAdminSeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminVideosNewRoute = AuthedAdminVideosNewRouteImport.update({
  id: '/videos/new',
  path: '/videos/new',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminSeriesNewRoute = AuthedAdminSeriesNewRouteImport.update({
  id: '/series/new',
  path: '/series/new',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminVideosIdEditRoute = AuthedAdminVideosIdEditRouteImport.update({
  id: '/videos/$id/edit',
  path: '/videos/$id/edit',
  getParentRoute: () => AuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/account': typeof AuthedAccountRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/favorites': typeof AuthedFavoritesRoute
  '/offline': typeof PublicOfflineRoute
  '/pricing': typeof PublicPricingRoute
  '/search': typeof PublicSearchRoute
  '/admin/comments': typeof AuthedAdminCommentsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/shows/$slug': typeof PublicShowsSlugRoute
  '/watch/$slug': typeof PublicWatchSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/mux': typeof ApiWebhooksMuxRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/shows/': typeof PublicShowsIndexRoute
  '/admin/series/new': typeof AuthedAdminSeriesNewRoute
  '/admin/videos/new': typeof AuthedAdminVideosNewRoute
  '/admin/series/': typeof AuthedAdminSeriesIndexRoute
  '/admin/videos/': typeof AuthedAdminVideosIndexRoute
  '/admin/videos/$id/edit': typeof AuthedAdminVideosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/account': typeof AuthedAccountRoute
  '/favorites': typeof AuthedFavoritesRoute
  '/offline': typeof PublicOfflineRoute
  '/pricing': typeof PublicPricingRoute
  '/search': typeof PublicSearchRoute
  '/admin/comments': typeof AuthedAdminCommentsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/shows/$slug': typeof PublicShowsSlugRoute
  '/watch/$slug': typeof PublicWatchSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/mux': typeof ApiWebhooksMuxRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/shows': typeof PublicShowsIndexRoute
  '/admin/series/new': typeof AuthedAdminSeriesNewRoute
  '/admin/videos/new': typeof AuthedAdminVideosNewRoute
  '/admin/series': typeof AuthedAdminSeriesIndexRoute
  '/admin/videos': typeof AuthedAdminVideosIndexRoute
  '/admin/videos/$id/edit': typeof AuthedAdminVideosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/favorites': typeof AuthedFavoritesRoute
  '/_public/offline': typeof PublicOfflineRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/': typeof PublicIndexRoute
  '/_authed/admin/comments': typeof AuthedAdminCommentsRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_public/shows/$slug': typeof PublicShowsSlugRoute
  '/_public/watch/$slug': typeof PublicWatchSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/mux': typeof ApiWebhooksMuxRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_public/shows/': typeof PublicShowsIndexRoute
  '/_authed/admin/series/new': typeof AuthedAdminSeriesNewRoute
  '/_authed/admin/videos/new': typeof AuthedAdminVideosNewRoute
  '/_authed/admin/series/': typeof AuthedAdminSeriesIndexRoute
  '/_authed/admin/videos/': typeof AuthedAdminVideosIndexRoute
  '/_authed/admin/videos/$id/edit': typeof AuthedAdminVideosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account'
    | '/admin'
    | '/favorites'
    | '/offline'
    | '/pricing'
    | '/search'
    | '/admin/comments'
    | '/admin/users'
    | '/shows/$slug'
    | '/watch/$slug'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/mux'
    | '/admin/'
    | '/shows/'
    | '/admin/series/new'
    | '/admin/videos/new'
    | '/admin/series/'
    | '/admin/videos/'
    | '/admin/videos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account'
    | '/favorites'
    | '/offline'
    | '/pricing'
    | '/search'
    | '/admin/comments'
    | '/admin/users'
    | '/shows/$slug'
    | '/watch/$slug'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/mux'
    | '/admin'
    | '/shows'
    | '/admin/series/new'
    | '/admin/videos/new'
    | '/admin/series'
    | '/admin/videos'
    | '/admin/videos/$id/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_authed'
    | '/_public'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authed/account'
    | '/_authed/admin'
    | '/_authed/favorites'
    | '/_public/offline'
    | '/_public/pricing'
    | '/_public/search'
    | '/_public/'
    | '/_authed/admin/comments'
    | '/_authed/admin/users'
    | '/_public/shows/$slug'
    | '/_public/watch/$slug'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/mux'
    | '/_authed/admin/'
    | '/_public/shows/'
    | '/_authed/admin/series/new'
    | '/_authed/admin/videos/new'
    | '/_authed/admin/series/'
    | '/_authed/admin/videos/'
    | '/_authed/admin/videos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhooksMuxRoute: typeof ApiWebhooksMuxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/offline': {
      id: '/_public/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof PublicOfflineRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/favorites': {
      id: '/_authed/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthedFavoritesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/shows/': {
      id: '/_public/shows/'
      path: '/shows'
      fullPath: '/shows/'
      preLoaderRoute: typeof PublicShowsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/api/webhooks/mux': {
      id: '/api/webhooks/mux'
      path: '/api/webhooks/mux'
      fullPath: '/api/webhooks/mux'
      preLoaderRoute: typeof ApiWebhooksMuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/watch/$slug': {
      id: '/_public/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof PublicWatchSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shows/$slug': {
      id: '/_public/shows/$slug'
      path: '/shows/$slug'
      fullPath: '/shows/$slug'
      preLoaderRoute: typeof PublicShowsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/comments': {
      id: '/_authed/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AuthedAdminCommentsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/videos/': {
      id: '/_authed/admin/videos/'
      path: '/videos'
      fullPath: '/admin/videos/'
      preLoaderRoute: typeof AuthedAdminVideosIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/series/': {
      id: '/_authed/admin/series/'
      path: '/series'
      fullPath: '/admin/series/'
      preLoaderRoute: typeof AuthedAdminSeriesIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/videos/new': {
      id: '/_authed/admin/videos/new'
      path: '/videos/new'
      fullPath: '/admin/videos/new'
      preLoaderRoute: typeof AuthedAdminVideosNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/series/new': {
      id: '/_authed/admin/series/new'
      path: '/series/new'
      fullPath: '/admin/series/new'
      preLoaderRoute: typeof AuthedAdminSeriesNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/videos/$id/edit': {
      id: '/_authed/admin/videos/$id/edit'
      path: '/videos/$id/edit'
      fullPath: '/admin/videos/$id/edit'
      preLoaderRoute: typeof AuthedAdminVideosIdEditRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthedAdminRouteChildren {
  AuthedAdminCommentsRoute: typeof AuthedAdminCommentsRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminSeriesNewRoute: typeof AuthedAdminSeriesNewRoute
  AuthedAdminVideosNewRoute: typeof AuthedAdminVideosNewRoute
  AuthedAdminSeriesIndexRoute: typeof AuthedAdminSeriesIndexRoute
  AuthedAdminVideosIndexRoute: typeof AuthedAdminVideosIndexRoute
  AuthedAdminVideosIdEditRoute: typeof AuthedAdminVideosIdEditRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminCommentsRoute: AuthedAdminCommentsRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminSeriesNewRoute: AuthedAdminSeriesNewRoute,
  AuthedAdminVideosNewRoute: AuthedAdminVideosNewRoute,
  AuthedAdminSeriesIndexRoute: AuthedAdminSeriesIndexRoute,
  AuthedAdminVideosIndexRoute: AuthedAdminVideosIndexRoute,
  AuthedAdminVideosIdEditRoute: AuthedAdminVideosIdEditRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedFavoritesRoute: typeof AuthedFavoritesRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedFavoritesRoute: AuthedFavoritesRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicOfflineRoute: typeof PublicOfflineRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicShowsSlugRoute: typeof PublicShowsSlugRoute
  PublicWatchSlugRoute: typeof PublicWatchSlugRoute
  PublicShowsIndexRoute: typeof PublicShowsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicOfflineRoute: PublicOfflineRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicShowsSlugRoute: PublicShowsSlugRoute,
  PublicWatchSlugRoute: PublicWatchSlugRoute,
  PublicShowsIndexRoute: PublicShowsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhooksMuxRoute: ApiWebhooksMuxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
